# Generated by Django 4.0.3 on 2022-04-05 07:25

import banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to_page', models.CharField(choices=[('Главная', 'Главная')], max_length=50, verbose_name='Относится к странице:')),
                ('order_number', models.PositiveSmallIntegerField(verbose_name='порядковый номер')),
                ('image', models.ImageField(blank=True, upload_to=banners.models.get_file_path, verbose_name='Картинка')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='Текст-описание')),
            ],
        ),
    ]
