# Generated by Django 3.2 on 2022-03-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Адрес')),
                ('longitude', models.FloatField(default=None, null=True, verbose_name='Долгота')),
                ('latitude', models.FloatField(default=None, null=True, verbose_name='Широта')),
                ('update_time', models.DateTimeField(default=None, null=True, verbose_name='Дата последнего обновления')),
            ],
        ),
    ]
