# Generated by Django 3.2 on 2022-03-08 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20220226_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelements',
            name='price_in_order',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='orderelements',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
