# Generated by Django 3.2 on 2022-03-08 10:58

from django.db import migrations


def count_price(apps, schema_editor):
    OrderElements = apps.get_model('foodcartapp', 'OrderElements')
    for element in OrderElements.objects.all():
        element.price_in_order = element.product.price * element.quantity
        element.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20220308_1055'),
    ]

    operations = [
        migrations.RunPython(count_price)
    ]
