# Generated by Django 3.2 on 2022-03-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, help_text='Пожелания клиента', verbose_name='Комментарии'),
        ),
    ]
