# Generated by Django 3.2 on 2022-03-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20220309_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], db_index=True, default='Наличностью', max_length=25, verbose_name='Способ оплаты'),
        ),
    ]
