# Generated by Django 3.2 on 2022-03-11 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно'), ('Не выбрано', 'Не выбрано')], db_index=True, default='Не выбрано', max_length=25, verbose_name='Способ оплаты'),
        ),
    ]
