# Generated by Django 3.2 on 2022-02-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20220223_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='phonenumber',
        ),
    ]
