# Generated by Django 3.2 on 2022-02-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_rename_name_order_firstname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderelements',
            options={'verbose_name': 'Составляющая заказа', 'verbose_name_plural': 'Элементы заказов'},
        ),
        migrations.AlterField(
            model_name='orderelements',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='foodcartapp.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderelements',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='foodcartapp.product', verbose_name='Продукт'),
        ),
    ]
