# Generated by Django 3.2 on 2022-03-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20220308_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Необработанный'), ('2', 'Обработан'), ('3', 'Готовится'), ('4', 'Доставляется'), ('5', 'Выполнен')], db_index=True, default=1, max_length=25, verbose_name='Cтатус'),
        ),
    ]
