# Generated by Django 3.2 on 2022-04-03 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20220322_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderelements',
            name='price_in_order',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
        ),
    ]
